// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package data

import ()

type Balance struct {
	Personid  int32
	Lastname  string
	Firstname string
	City      string
	Balance   int64
}
