// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: query.sql

package data

import ()

type InsertBalancesParams struct {
	Lastname  string
	Firstname string
	City      string
	Balance   int64
}
