// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: batch.go

package data

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v4"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertBalances = `-- name: InsertBalances :batchexec
INSERT INTO balances (LastName, FirstName, City, Balance) VALUES ($1, $2, $3, $4)
`

type InsertBalancesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertBalancesParams struct {
	Lastname  string
	Firstname string
	City      string
	Balance   int64
}

func (q *Queries) InsertBalances(ctx context.Context, arg []InsertBalancesParams) *InsertBalancesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Lastname,
			a.Firstname,
			a.City,
			a.Balance,
		}
		batch.Queue(insertBalances, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertBalancesBatchResults{br, len(arg), false}
}

func (b *InsertBalancesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertBalancesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
