version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    command: postgres -c 'max_connections=9000'

  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database